namespace AgentPlatform.Domain.Aggregates.AgentRuns;

/// <summary>
/// A persisted history entry for a single agent run (goal-driven agentic control loop).
/// Records enough metadata to let operators browse past runs, reopen their final answer,
/// and jump to the generated artifacts (keyed by <see cref="RunId"/> → data/agent-runs/{runId}).
/// </summary>
public sealed class AgentRunRecord
{
    /// <summary>Primary key (surrogate).</summary>
    public long Id { get; private set; }

    /// <summary>Tenant that owns the run (for isolation).</summary>
    public Guid TenantId { get; private set; }

    /// <summary>The agent that was driven.</summary>
    public Guid AgentId { get; private set; }

    /// <summary>Snapshot of the agent's name at run time (survives agent rename).</summary>
    public string AgentName { get; private set; } = null!;

    /// <summary>The run identifier, also used as the artifact directory name.</summary>
    public Guid RunId { get; private set; }

    /// <summary>The user-supplied goal the agent worked toward.</summary>
    public string Goal { get; private set; } = null!;

    /// <summary>The model's final answer (may be truncated for very long outputs).</summary>
    public string? FinalAnswer { get; private set; }

    /// <summary>Number of plan/act/observe iterations performed.</summary>
    public int Iterations { get; private set; }

    /// <summary>Total prompt tokens consumed across the loop.</summary>
    public int TotalTokensIn { get; private set; }

    /// <summary>Total completion tokens produced across the loop.</summary>
    public int TotalTokensOut { get; private set; }

    /// <summary>Number of artifact files generated by the run.</summary>
    public int ArtifactCount { get; private set; }

    /// <summary>Run outcome: Completed / Failed / Cancelled.</summary>
    public AgentRunStatus Status { get; private set; }

    /// <summary>Wall-clock duration of the run in milliseconds.</summary>
    public long DurationMs { get; private set; }

    /// <summary>Error detail when <see cref="Status"/> is Failed.</summary>
    public string? ErrorMessage { get; private set; }

    /// <summary>UTC creation timestamp.</summary>
    public DateTime CreatedAt { get; private set; } = DateTime.UtcNow;

    // EF Core / ORM constructor.
    private AgentRunRecord()
    {
    }

    public AgentRunRecord(
        Guid tenantId,
        Guid agentId,
        string agentName,
        Guid runId,
        string goal,
        AgentRunStatus status,
        long durationMs,
        int iterations = 0,
        int totalTokensIn = 0,
        int totalTokensOut = 0,
        int artifactCount = 0,
        string? finalAnswer = null,
        string? errorMessage = null)
    {
        ArgumentNullException.ThrowIfNull(agentName);
        ArgumentNullException.ThrowIfNull(goal);

        TenantId = tenantId;
        AgentId = agentId;
        AgentName = agentName;
        RunId = runId;
        Goal = goal;
        Status = status;
        DurationMs = durationMs;
        Iterations = iterations;
        TotalTokensIn = totalTokensIn;
        TotalTokensOut = totalTokensOut;
        ArtifactCount = artifactCount;
        FinalAnswer = finalAnswer;
        ErrorMessage = errorMessage;
    }
}
