using AgentPlatform.Application.Abstractions;
using AgentPlatform.Domain.ValueObjects;

namespace AgentPlatform.Application.Conversations.Commands.SendMessage;

/// <summary>
/// Represents a command to send a message within an existing conversation, optionally
/// augmenting the request with vector search context and a preferred model.
/// </summary>
/// <param name="ConversationId">The unique identifier of the conversation to send the message to.</param>
/// <param name="Content">The text content of the user's message.</param>
/// <param name="SearchQuery">An optional query used to retrieve relevant context from the vector store.</param>
/// <param name="Model">An optional model identifier to prefer during routing.</param>
public record SendMessageCommand(
    Guid ConversationId,
    string Content,
    string? SearchQuery = null,
    string? Model = null
) : ICommand<SendMessageResult>;

/// <summary>
/// Represents the result of sending a message, including the agent's reply and token usage.
/// </summary>
/// <param name="Reply">The reply text generated by the model.</param>
/// <param name="ModelId">The identifier of the model that produced the reply.</param>
/// <param name="TokenUsage">The token usage incurred by the request, if reported.</param>
public record SendMessageResult(
    string Reply,
    string ModelId,
    TokenUsage? TokenUsage);
