using AgentPlatform.Domain.Aggregates.PlatformModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AgentPlatform.Infrastructure.Persistence.Configurations;

/// <summary>
/// Configures the EF Core mapping for the <see cref="PlatformModel"/> aggregate.
/// Maps to the PlatformModels table. Platform models are NOT tenant-scoped — the central
/// query filter in <c>AppDbContext.OnModelCreating</c> only applies to <see cref="ITenantScoped"/> entities.
/// </summary>
internal sealed class PlatformModelConfiguration : IEntityTypeConfiguration<PlatformModel>
{
    public void Configure(EntityTypeBuilder<PlatformModel> builder)
    {
        builder.ToTable("PlatformModels");
        builder.HasKey(k => k.Id);
        // Guid is generated by the caller; never let EF treat it as store-generated (avoids UPDATE-on-INSERT trap).
        builder.Property(k => k.Id).ValueGeneratedNever();
        builder.Property(k => k.Provider).IsRequired().HasMaxLength(50);
        builder.Property(k => k.ModelName).IsRequired().HasMaxLength(200);
        builder.Property(k => k.BaseUrl).HasMaxLength(500);
        builder.Property(k => k.EncryptedApiKey).HasMaxLength(2000);
        builder.Property(k => k.ApiKeyPrefix).HasMaxLength(20);
        builder.Property(k => k.DisplayName).HasMaxLength(200);
        builder.Property(k => k.Priority).IsRequired();
        builder.Property(k => k.IsEnabled).IsRequired();
        builder.Property(k => k.CreatedAt).IsRequired();
        builder.Property(k => k.UpdatedAt).IsRequired();
    }
}
