using AgentPlatform.Domain.Aggregates.TenantCredentials;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AgentPlatform.Infrastructure.Persistence.Configurations;

/// <summary>
/// Configures the EF Core mapping for the <see cref="TenantCredentialSetting"/> aggregate.
/// Maps to the TenantCredentialSettings table with encrypted key storage and tenant isolation.
/// The tenant query filter is applied centrally in <c>AppDbContext.OnModelCreating</c>.
/// </summary>
internal sealed class TenantCredentialSettingConfiguration : IEntityTypeConfiguration<TenantCredentialSetting>
{
    public void Configure(EntityTypeBuilder<TenantCredentialSetting> builder)
    {
        builder.ToTable("TenantCredentialSettings");
        builder.HasKey(k => k.Id);
        // Guid is generated by the caller; never let EF treat it as store-generated (avoids UPDATE-on-INSERT trap).
        builder.Property(k => k.Id).ValueGeneratedNever();
        builder.Property(k => k.TenantId).IsRequired();
        builder.Property(k => k.Category).IsRequired();
        builder.Property(k => k.Provider).IsRequired().HasMaxLength(50);
        builder.Property(k => k.EncryptedApiKey).IsRequired().HasMaxLength(2000);
        builder.Property(k => k.ApiKeyPrefix).IsRequired().HasMaxLength(20);
        builder.Property(k => k.BaseUrl).HasMaxLength(500);
        builder.Property(k => k.ModelName).HasMaxLength(200);
        builder.Property(k => k.IsEnabled).IsRequired();
        builder.Property(k => k.CreatedAt).IsRequired();
        builder.Property(k => k.UpdatedAt).IsRequired();
        builder.HasIndex(k => new { k.TenantId, k.Category }).IsUnique();
    }
}
