using AgentPlatform.Domain.Aggregates.Workspaces;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AgentPlatform.Infrastructure.Persistence.Configurations;

/// <summary>
/// Configures the EF Core mapping for the <see cref="WorkspaceMember"/> aggregate (F35).
/// (WorkspaceId, UserId) is unique — a user joins a workspace at most once;
/// the tenant query filter is applied centrally in <c>AppDbContext.OnModelCreating</c>.
/// </summary>
internal sealed class WorkspaceMemberConfiguration : IEntityTypeConfiguration<WorkspaceMember>
{
    public void Configure(EntityTypeBuilder<WorkspaceMember> builder)
    {
        builder.ToTable("WorkspaceMembers");
        builder.HasKey(k => k.Id);
        // Guid is generated by the caller; never let EF treat it as store-generated (avoids UPDATE-on-INSERT trap).
        builder.Property(k => k.Id).ValueGeneratedNever();
        builder.Property(k => k.TenantId).IsRequired();
        builder.Property(k => k.WorkspaceId).IsRequired();
        builder.Property(k => k.UserId).IsRequired();
        builder.Property(k => k.CreatedAt).IsRequired();
        builder.HasIndex(k => new { k.WorkspaceId, k.UserId }).IsUnique();
        builder.HasIndex(k => k.UserId);
    }
}
