using AgentPlatform.Domain.Aggregates.Workspaces;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AgentPlatform.Infrastructure.Persistence.Configurations;

/// <summary>
/// Configures the EF Core mapping for the <see cref="Workspace"/> aggregate (F35).
/// Name is unique per tenant; the tenant query filter is applied centrally in
/// <c>AppDbContext.OnModelCreating</c>.
/// </summary>
internal sealed class WorkspaceConfiguration : IEntityTypeConfiguration<Workspace>
{
    public void Configure(EntityTypeBuilder<Workspace> builder)
    {
        builder.ToTable("Workspaces");
        builder.HasKey(k => k.Id);
        // Guid is generated by the caller; never let EF treat it as store-generated (avoids UPDATE-on-INSERT trap).
        builder.Property(k => k.Id).ValueGeneratedNever();
        builder.Property(k => k.TenantId).IsRequired();
        builder.Property(k => k.Name).IsRequired().HasMaxLength(100);
        builder.Property(k => k.Description).HasMaxLength(500);
        builder.Property(k => k.IsDefault).IsRequired();
        builder.Property(k => k.CreatedAt).IsRequired();
        builder.Property(k => k.UpdatedAt).IsRequired();
        // 工作空间名称在同一租户内唯一。
        builder.HasIndex(k => new { k.TenantId, k.Name }).IsUnique();
    }
}
