using AgentPlatform.Application.Abstractions;

namespace AgentPlatform.Application.Agents.Agentic;

/// <summary>
/// A single server-sent event emitted while an agentic run is in progress.
/// The page consumes these to render the "thinking process" (tool calls / results)
/// in real time and to stream the final answer token-by-token.
/// </summary>
/// <param name="Type">
/// One of: <c>iteration</c> (a new plan/act/observe round started),
/// <c>tool_call</c> (the model proposed a tool invocation),
/// <c>tool_result</c> (the platform executed it and got an outcome),
/// <c>answer_delta</c> (a chunk of the streaming final answer),
/// <c>done</c> (the run finished; carries the full answer + token counts),
/// <c>error</c> (the run failed; <c>Error</c> carries the message).
/// </param>
/// <param name="Iteration">Iteration index for <c>iteration</c> / <c>tool_call</c> / <c>tool_result</c>.</param>
/// <param name="ToolName">Tool name for <c>tool_call</c> / <c>tool_result</c>.</param>
/// <param name="ArgumentsJson">Tool arguments (JSON) for <c>tool_call</c>.</param>
/// <param name="Output">Tool output for <c>tool_result</c>.</param>
/// <param name="Success">Whether the tool executed successfully (<c>tool_result</c>).</param>
/// <param name="Delta">A text chunk of the streaming final answer (<c>answer_delta</c>).</param>
/// <param name="FinalAnswer">The complete final answer (<c>done</c>).</param>
/// <param name="TokensIn">Total prompt tokens consumed (<c>done</c>).</param>
/// <param name="TokensOut">Total completion tokens produced (<c>done</c>).</param>
/// <param name="Error">Failure message (<c>error</c>).</param>
/// <param name="Artifacts">Files generated by the run, persisted for in-platform preview/download (<c>done</c>).</param>
/// <param name="RunId">The run identifier, emitted on <c>run_start</c> so the UI can fetch artifacts afterwards.</param>
public sealed record AgenticStreamEvent(
    string Type,
    int? Iteration = null,
    string? ToolName = null,
    string? ArgumentsJson = null,
    string? Output = null,
    bool? Success = null,
    string? Delta = null,
    string? FinalAnswer = null,
    int? TokensIn = null,
    int? TokensOut = null,
    string? Error = null,
    IReadOnlyList<ArtifactEntry>? Artifacts = null,
    string? RunId = null);
