using AgentPlatform.Domain.Abstractions;
using AgentPlatform.Domain.Enums;

namespace AgentPlatform.Domain.Aggregates.TenantCredentials;

/// <summary>
/// Tenant-scoped external API credential (LLM model key or search key), stored encrypted at rest.
/// Plaintext keys are never persisted; only the AES-256-GCM ciphertext and an 8-char prefix are stored.
/// Encryption/decryption is performed in the application/infrastructure layer via
/// <see cref="AgentPlatform.Application.Abstractions.IApiKeyEncryptionService"/>; this aggregate only holds the ciphertext.
/// </summary>
public sealed class TenantCredentialSetting : ITenantScoped, IAggregateRoot
{
    /// <summary>Gets the unique identifier. Generated by the caller; EF is configured with <c>ValueGeneratedNever</c>.</summary>
    public Guid Id { get; private init; }

    /// <summary>Gets the owning tenant (enables automatic <c>HasQueryFilter</c> isolation).</summary>
    public Guid TenantId { get; private init; }

    /// <summary>Gets the credential category (Model / Search).</summary>
    public CredentialCategory Category { get; private set; }

    /// <summary>Gets the provider name (e.g. "DeepSeek", "SerpApi").</summary>
    public string Provider { get; private set; } = null!;

    /// <summary>Gets the encrypted API key (ciphertext produced by <c>IApiKeyEncryptionService</c>). Never the plaintext.</summary>
    public string EncryptedApiKey { get; private set; } = null!;

    /// <summary>Gets the human-readable prefix (first 8 chars of the plaintext key) used for masked display.</summary>
    public string ApiKeyPrefix { get; private set; } = null!;

    /// <summary>Gets the optional base URL (model provider endpoint / custom OpenAI-compatible base).</summary>
    public string? BaseUrl { get; private set; }

    /// <summary>Gets the optional model name (model category only).</summary>
    public string? ModelName { get; private set; }

    /// <summary>Gets whether this credential is currently active.</summary>
    public bool IsEnabled { get; private set; }

    /// <summary>Gets when this setting was created.</summary>
    public DateTime CreatedAt { get; private init; }

    /// <summary>Gets when this setting was last updated.</summary>
    public DateTime UpdatedAt { get; private set; }

    private readonly List<IDomainEvent> _domainEvents = [];

    private TenantCredentialSetting() { }

    /// <summary>
    /// Initializes a new instance of the <see cref="TenantCredentialSetting"/> class.
    /// The caller must pre-encrypt the plaintext key via <c>IApiKeyEncryptionService.EncryptKey</c>
    /// and pass the resulting ciphertext + prefix.
    /// </summary>
    public TenantCredentialSetting(
        Guid id,
        Guid tenantId,
        CredentialCategory category,
        string provider,
        string encryptedApiKey,
        string keyPrefix,
        string? baseUrl,
        string? modelName,
        bool isEnabled)
    {
        if (id == Guid.Empty)
            throw new ArgumentException("Id must not be empty.", nameof(id));
        if (tenantId == Guid.Empty)
            throw new ArgumentException("TenantId must not be empty.", nameof(tenantId));
        ArgumentException.ThrowIfNullOrWhiteSpace(provider);
        ArgumentException.ThrowIfNullOrWhiteSpace(encryptedApiKey);
        ArgumentException.ThrowIfNullOrWhiteSpace(keyPrefix);

        Id = id;
        TenantId = tenantId;
        Category = category;
        Provider = provider;
        EncryptedApiKey = encryptedApiKey;
        ApiKeyPrefix = keyPrefix;
        BaseUrl = baseUrl;
        ModelName = modelName;
        IsEnabled = isEnabled;
        CreatedAt = DateTime.UtcNow;
        UpdatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Updates the credential in place. Callers must pass the freshly-encrypted key + prefix
    /// (encryption is performed in the application layer, not here).
    /// </summary>
    public void Update(string provider, string encryptedApiKey, string keyPrefix, string? baseUrl, string? modelName, bool isEnabled)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(provider);
        ArgumentException.ThrowIfNullOrWhiteSpace(encryptedApiKey);
        ArgumentException.ThrowIfNullOrWhiteSpace(keyPrefix);

        Provider = provider;
        EncryptedApiKey = encryptedApiKey;
        ApiKeyPrefix = keyPrefix;
        BaseUrl = baseUrl;
        ModelName = modelName;
        IsEnabled = isEnabled;
        UpdatedAt = DateTime.UtcNow;
    }

    /// <summary>Gets the collection of domain events.</summary>
    public IReadOnlyCollection<IDomainEvent> DomainEvents => _domainEvents.AsReadOnly();

    /// <summary>Clears all pending domain events.</summary>
    public void ClearDomainEvents() => _domainEvents.Clear();
}
