// <auto-generated />
using System;
using AgentPlatform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824013403_AddDurableExecutionCheckpoint")]
    partial class AddDurableExecutionCheckpoint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.AgentConfigurations.AgentConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentTypeCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("YamlContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentTypeCode");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("AgentConfigurations", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.AgentRoleDefinitions.AgentRoleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleCode")
                        .IsUnique();

                    b.ToTable("AgentRoleDefinitions", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.AgentRuns.AgentRunRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ArtifactCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalAnswer")
                        .HasColumnType("text");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Iterations")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTokensIn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTokensOut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "AgentId", "CreatedAt");

                    b.ToTable("AgentRunRecords", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.Agents.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedToolNamesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]")
                        .HasColumnName("AllowedToolNamesJson");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxIterations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("MaxIterations");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StopCriteria")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("StopCriteria");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.ApiKeys.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedKeyHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("KeyVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RolesCsv")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsActive");

                    b.HasIndex("IsActive", "RevokedAt", "ExpiresAt");

                    b.ToTable("ApiKeys", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.AuditLogs.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.Conversations.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectionName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("KnowledgeBaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.Conversations.ConversationWorkflowBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ConversationId");

                    b.HasIndex("TenantId", "WorkflowId");

                    b.ToTable("ConversationWorkflowBindings", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.Debug.DebugSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStepOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VariablesJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "WorkflowId");

                    b.ToTable("DebugSessions", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.Evaluation.EvaluationDataset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("EvaluationDatasets", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.ExecutionLogs.ExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckpointData")
                        .HasColumnType("text");

                    b.Property<int>("CheckpointVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("WorkflowId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("ExecutionLogs", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.HumanApprovals.HumanApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedInput")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.HasIndex("TenantId", "WorkflowId", "NodeName", "Status");

                    b.ToTable("HumanApprovals", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.KnowledgeBases.KnowledgeBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KnowledgeBases", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.KnowledgeBases.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KnowledgeBaseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeBaseId");

                    b.ToTable("KnowledgeDocument", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.PublishedWorkflows.PublishedWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApiKeyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSchemaJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique();

                    b.HasIndex("TenantId", "WorkflowId");

                    b.ToTable("PublishedWorkflows", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.TenantCredentials.TenantCredentialSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeyPrefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedApiKey")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Category");

                    b.ToTable("TenantCredentialSettings", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.ToolDefinitions.ToolDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("HandlerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersSchema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillPluginName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ToolDefinitions", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.WorkflowTemplates.WorkflowTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("WorkflowTemplates", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.WorkflowTriggers.WorkflowTrigger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cron")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerToken")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NextRunAt");

                    b.HasIndex("TriggerToken");

                    b.HasIndex("TenantId", "WorkflowId", "Type")
                        .IsUnique();

                    b.ToTable("WorkflowTriggers", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.Workflows.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("_isDag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDag");

                    b.HasKey("Id");

                    b.ToTable("Workflows", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.Workflows.WorkflowVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "VersionNumber");

                    b.ToTable("WorkflowVersions", (string)null);
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.AgentConfigurations.AgentConfiguration", b =>
                {
                    b.OwnsOne("AgentPlatform.Domain.ValueObjects.ConfigurationVersion", "Version", b1 =>
                        {
                            b1.Property<Guid>("AgentConfigurationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ChangeLog")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT")
                                .HasColumnName("VersionChangeLog");

                            b1.Property<int>("Major")
                                .HasColumnType("INTEGER")
                                .HasColumnName("VersionMajor");

                            b1.Property<int>("Minor")
                                .HasColumnType("INTEGER")
                                .HasColumnName("VersionMinor");

                            b1.Property<int>("Patch")
                                .HasColumnType("INTEGER")
                                .HasColumnName("VersionPatch");

                            b1.HasKey("AgentConfigurationId");

                            b1.ToTable("AgentConfigurations");

                            b1.WithOwner()
                                .HasForeignKey("AgentConfigurationId");
                        });

                    b.Navigation("Version")
                        .IsRequired();
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.Agents.Agent", b =>
                {
                    b.OwnsOne("AgentPlatform.Domain.ValueObjects.AgentType", "Role", b1 =>
                        {
                            b1.Property<Guid>("AgentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("RoleDescription");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("RoleDisplayName");

                            b1.Property<string>("RoleCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("RoleCode");

                            b1.HasKey("AgentId");

                            b1.ToTable("Agents");

                            b1.WithOwner()
                                .HasForeignKey("AgentId");
                        });

                    b.OwnsOne("AgentPlatform.Domain.ValueObjects.ModelEndpoint", "ModelEndpoint", b1 =>
                        {
                            b1.Property<Guid>("AgentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ApiUrl")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("ModelApiUrl");

                            b1.Property<int>("MaxTokens")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ModelMaxTokens");

                            b1.Property<string>("ModelName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("ModelName");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("ModelProvider");

                            b1.Property<double>("Temperature")
                                .HasColumnType("REAL")
                                .HasColumnName("ModelTemperature");

                            b1.HasKey("AgentId");

                            b1.ToTable("Agents");

                            b1.WithOwner()
                                .HasForeignKey("AgentId");
                        });

                    b.Navigation("ModelEndpoint")
                        .IsRequired();

                    b.Navigation("Role")
                        .IsRequired();
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.Conversations.Conversation", b =>
                {
                    b.OwnsOne("AgentPlatform.Domain.ValueObjects.TokenUsage", "TotalTokenUsage", b1 =>
                        {
                            b1.Property<Guid>("ConversationId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("CompletionTokens")
                                .HasColumnType("INTEGER")
                                .HasColumnName("CompletionTokens");

                            b1.Property<int>("PromptTokens")
                                .HasColumnType("INTEGER")
                                .HasColumnName("PromptTokens");

                            b1.HasKey("ConversationId");

                            b1.ToTable("Conversations");

                            b1.WithOwner()
                                .HasForeignKey("ConversationId");
                        });

                    b.OwnsMany("AgentPlatform.Domain.Aggregates.Conversations.Message", "Messages", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(16000)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ConversationId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("ToolCalls")
                                .HasMaxLength(8000)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ConversationId");

                            b1.ToTable("Message");

                            b1.WithOwner()
                                .HasForeignKey("ConversationId");

                            b1.OwnsOne("AgentPlatform.Domain.ValueObjects.TokenUsage", "TokenUsage", b2 =>
                                {
                                    b2.Property<Guid>("MessageId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("CompletionTokens")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("MsgCompletionTokens");

                                    b2.Property<int>("PromptTokens")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("MsgPromptTokens");

                                    b2.HasKey("MessageId");

                                    b2.ToTable("Message");

                                    b2.WithOwner()
                                        .HasForeignKey("MessageId");
                                });

                            b1.Navigation("TokenUsage");
                        });

                    b.Navigation("Messages");

                    b.Navigation("TotalTokenUsage")
                        .IsRequired();
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.Evaluation.EvaluationDataset", b =>
                {
                    b.OwnsMany("AgentPlatform.Domain.Aggregates.Evaluation.EvaluationCase", "Cases", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("EvaluationDatasetId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ExpectedOutput")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Input")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("TEXT");

                            b1.Property<int>("MatchMode")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("EvaluationDatasetId");

                            b1.ToTable("EvaluationCases", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EvaluationDatasetId");
                        });

                    b.Navigation("Cases");
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.ExecutionLogs.ExecutionLog", b =>
                {
                    b.OwnsMany("AgentPlatform.Domain.Aggregates.ExecutionLogs.ExecutionLogEntry", "Entries", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CompletedAt")
                                .HasColumnType("TEXT");

                            b1.Property<TimeSpan>("Duration")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ErrorDetail")
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ExecutionLogId")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("NodeType")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Result")
                                .HasMaxLength(4000)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("StartedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("StepName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<int>("StepOrder")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TokensIn")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TokensOut")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("ExecutionLogId");

                            b1.ToTable("ExecutionLogEntries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ExecutionLogId");
                        });

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.KnowledgeBases.KnowledgeDocument", b =>
                {
                    b.HasOne("AgentPlatform.Domain.Aggregates.KnowledgeBases.KnowledgeBase", null)
                        .WithMany("Documents")
                        .HasForeignKey("KnowledgeBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.Workflows.Workflow", b =>
                {
                    b.OwnsMany("AgentPlatform.Domain.Aggregates.Workflows.WorkflowEdge", "Edges", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Label")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("SourceNodeId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("TargetNodeId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("WorkflowId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkflowId");

                            b1.ToTable("WorkflowEdge");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowId");
                        });

                    b.OwnsMany("AgentPlatform.Domain.Aggregates.Workflows.WorkflowNode", "Nodes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("AssignedAgentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ConfigJson")
                                .IsRequired()
                                .HasMaxLength(16000)
                                .HasColumnType("TEXT");

                            b1.Property<string>("ErrorDetail")
                                .HasMaxLength(8000)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<int>("Order")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("PositionX")
                                .HasColumnType("REAL");

                            b1.Property<double>("PositionY")
                                .HasColumnType("REAL");

                            b1.Property<string>("Result")
                                .HasMaxLength(16000)
                                .HasColumnType("TEXT");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("WorkflowId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkflowId");

                            b1.ToTable("WorkflowNode");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowId");
                        });

                    b.OwnsMany("AgentPlatform.Domain.Aggregates.Workflows.WorkflowStep", "Steps", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("AssignedAgentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ErrorDetail")
                                .HasMaxLength(8000)
                                .HasColumnType("TEXT");

                            b1.Property<int>("Order")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Result")
                                .HasMaxLength(16000)
                                .HasColumnType("TEXT");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("StepName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("WorkflowId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkflowId");

                            b1.ToTable("WorkflowStep");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowId");
                        });

                    b.Navigation("Edges");

                    b.Navigation("Nodes");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("AgentPlatform.Domain.Aggregates.KnowledgeBases.KnowledgeBase", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
