using AgentPlatform.Domain.ValueObjects;

namespace AgentPlatform.Api.Models;

/// <summary>
/// Represents the API response payload returned after sending a message to a conversation,
/// containing the agent's reply, the model that produced it, and optional token usage metrics.
/// </summary>
/// <param name="Reply">The reply text generated by the agent.</param>
/// <param name="ModelId">The identifier of the model that generated the reply.</param>
/// <param name="TokenUsage">The token usage breakdown for the request, if available.</param>
public record SendMessageResponse(
    string Reply,
    string ModelId,
    TokenUsage? TokenUsage);
