using AgentPlatform.Domain.Enums;
using AgentPlatform.Domain.ValueObjects;

namespace AgentPlatform.Application.Abstractions;

/// <summary>
/// Provides operations for interacting with an LLM model, including chat completion, streaming, and health checks.
/// </summary>
public interface IModelClient
{
    /// <summary>
    /// Sends a chat completion request to the specified model and returns the full response.
    /// </summary>
    /// <param name="modelId">The unique identifier of the model to call.</param>
    /// <param name="messages">The read-only list of chat messages to send.</param>
    /// <param name="ct">A cancellation token to observe while waiting for the operation to complete.</param>
    /// <returns>A task whose result contains the model's chat response.</returns>
    Task<ModelResponse> ChatAsync(
        string modelId,
        IReadOnlyList<ChatMessage> messages,
        CancellationToken ct = default);

    /// <summary>
    /// Sends a chat completion request to the specified model and streams the response token-by-token.
    /// </summary>
    /// <param name="modelId">The unique identifier of the model to call.</param>
    /// <param name="messages">The read-only list of chat messages to send.</param>
    /// <param name="ct">A cancellation token to observe while waiting for the operation to complete.</param>
    /// <returns>An asynchronous enumerable of response chunks as they arrive.</returns>
    IAsyncEnumerable<string> ChatStreamAsync(
        string modelId,
        IReadOnlyList<ChatMessage> messages,
        CancellationToken ct = default);

    /// <summary>
    /// Retrieves the current health and rate-limit status of the specified model.
    /// </summary>
    /// <param name="modelId">The unique identifier of the model to check.</param>
    /// <param name="ct">A cancellation token to observe while waiting for the operation to complete.</param>
    /// <returns>A task whose result contains the model's health information.</returns>
    Task<ModelHealth> GetHealthAsync(string modelId, CancellationToken ct = default);
}

/// <summary>
/// Represents the response returned by a model after a chat completion.
/// </summary>
/// <param name="Content">The text content generated by the model.</param>
/// <param name="TokenUsage">The token usage incurred by the request, if reported by the provider.</param>
/// <param name="ModelId">The unique identifier of the model that produced this response.</param>
/// <param name="FinishReason">The reason the model stopped generating (e.g., "stop", "length").</param>
public record ModelResponse(
    string Content,
    TokenUsage? TokenUsage,
    string ModelId,
    string FinishReason);

/// <summary>
/// Represents a single message within a chat conversation, including its role and optional tool-call metadata.
/// </summary>
/// <param name="Role">The role of the message sender (e.g., System, User, Assistant).</param>
/// <param name="Content">The textual content of the message.</param>
/// <param name="ToolCallId">The identifier of the tool call this message is associated with, if any.</param>
/// <param name="ToolName">The name of the tool invoked, if this message represents a tool call or response.</param>
public record ChatMessage(
    MessageRole Role,
    string Content,
    string? ToolCallId = null,
    string? ToolName = null);

/// <summary>
/// Represents the health and rate-limit status of a model at a point in time.
/// </summary>
/// <param name="ModelId">The unique identifier of the model.</param>
/// <param name="IsAvailable">A value indicating whether the model is currently available to serve requests.</param>
/// <param name="AvgLatency">The average response latency, if measured.</param>
/// <param name="RateLimitRemaining">The remaining number of requests allowed under the current rate limit, if applicable.</param>
public record ModelHealth(
    string ModelId,
    bool IsAvailable,
    TimeSpan? AvgLatency,
    int? RateLimitRemaining);
