using AgentPlatform.Domain.Abstractions;

namespace AgentPlatform.Domain.Aggregates.PlatformModels;

/// <summary>
/// 平台级（非租户隔离）默认模型目录。运营方配置的后端 LLM 模型，作为所有租户在无 BYO 凭据时的
/// 默认回退。密钥以 AES-256-GCM 密文落库（与 <see cref="AgentPlatform.Domain.Aggregates.TenantCredentials.TenantCredentialSetting"/> 一致），
/// 明文仅服务端内部解密使用，绝不外泄。
///
/// 与租户凭据不同，平台模型**不实现** <see cref="ITenantScoped"/> —— 它是全局共享的，不受
/// <see cref="AppDbContext"/> 的租户查询过滤约束。
/// </summary>
public sealed class PlatformModel : IAggregateRoot
{
    /// <summary>Gets the unique identifier. Generated by the caller; EF is configured with <c>ValueGeneratedNever</c>.</summary>
    public Guid Id { get; private init; }

    /// <summary>Gets the provider name (e.g. "openai", "deepseek", "vllm", "custom").</summary>
    public string Provider { get; private set; } = null!;

    /// <summary>Gets the model name / id used as the routing candidate key (e.g. "gpt-4o-mini", "agnes-2.5-flash").</summary>
    public string ModelName { get; private set; } = null!;

    /// <summary>Gets the optional OpenAI-compatible base URL for the provider endpoint (null = provider default).</summary>
    public string? BaseUrl { get; private set; }

    /// <summary>Gets the encrypted API key (ciphertext produced by <c>IApiKeyEncryptionService</c>). Never the plaintext.</summary>
    public string? EncryptedApiKey { get; private set; }

    /// <summary>Gets the human-readable prefix (first 8 chars of the plaintext key) used for masked display in admin UIs.</summary>
    public string? ApiKeyPrefix { get; private set; }

    /// <summary>Gets the optional display name shown in model picker UIs (e.g. "Agnes Flash 2.5").</summary>
    public string? DisplayName { get; private set; }

    /// <summary>Gets the routing priority; higher values are preferred first when multiple platform models exist.</summary>
    public int Priority { get; private set; }

    /// <summary>Gets whether this platform model is currently active for routing.</summary>
    public bool IsEnabled { get; private set; }

    /// <summary>Gets when this record was created.</summary>
    public DateTime CreatedAt { get; private init; }

    /// <summary>Gets when this record was last updated.</summary>
    public DateTime UpdatedAt { get; private set; }

    private readonly List<IDomainEvent> _domainEvents = [];

    private PlatformModel() { }

    /// <summary>
    /// Initializes a new instance of the <see cref="PlatformModel"/> class.
    /// The caller must pre-encrypt the plaintext key via <c>IApiKeyEncryptionService.EncryptKey</c>
    /// and pass the resulting ciphertext + prefix (same contract as TenantCredentialSetting).
    /// </summary>
    public PlatformModel(
        Guid id,
        string provider,
        string modelName,
        int priority,
        bool isEnabled,
        string? baseUrl = null,
        string? encryptedApiKey = null,
        string? apiKeyPrefix = null,
        string? displayName = null)
    {
        if (id == Guid.Empty)
            throw new ArgumentException("Id must not be empty.", nameof(id));
        ArgumentException.ThrowIfNullOrWhiteSpace(provider);
        ArgumentException.ThrowIfNullOrWhiteSpace(modelName);

        Id = id;
        Provider = provider;
        ModelName = modelName;
        Priority = priority;
        IsEnabled = isEnabled;
        BaseUrl = baseUrl;
        EncryptedApiKey = encryptedApiKey;
        ApiKeyPrefix = apiKeyPrefix;
        DisplayName = displayName;
        CreatedAt = DateTime.UtcNow;
        UpdatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Updates the platform model in place. Callers must pass the freshly-encrypted key + prefix
    /// (encryption is performed in the application layer, not here).
    /// </summary>
    public void Update(string provider, string modelName, int priority, bool isEnabled,
        string? baseUrl = null, string? encryptedApiKey = null, string? apiKeyPrefix = null, string? displayName = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(provider);
        ArgumentException.ThrowIfNullOrWhiteSpace(modelName);

        Provider = provider;
        ModelName = modelName;
        Priority = priority;
        IsEnabled = isEnabled;
        BaseUrl = baseUrl;
        EncryptedApiKey = encryptedApiKey;
        ApiKeyPrefix = apiKeyPrefix;
        DisplayName = displayName;
        UpdatedAt = DateTime.UtcNow;
    }

    /// <summary>Gets the collection of domain events.</summary>
    public IReadOnlyCollection<IDomainEvent> DomainEvents => _domainEvents.AsReadOnly();

    /// <summary>Clears all pending domain events.</summary>
    public void ClearDomainEvents() => _domainEvents.Clear();
}
